# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20161017_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
